name: grav_comp_demo

dynamixel:
  # USB port name given by the command: ls /dev/serial/by-id/
  dynamixel_port: "usb-FTDI_USB__-__Serial_Converter_FTA2U4GA-if00-port0"
  # Servo types
  servo_types: [
    "XC330_T288_T", "XM430_W210_T", "XM430_W210_T",
    "XC330_T288_T", "XC330_T288_T", "XC330_T288_T", "XC330_T288_T"
  ]
  # Servo joint directions to match that of the leader arm
  joint_signs: [1, -1, -1, -1, 1, 1, 1]

arm_teleop:
  # URDF used for creating leader arm dynamics model to compute gravity compensation
  # GELLO-specific path - completely independent from lab42
  leader_urdf: "gello/factr/urdf/yam_active_gello/robot.urdf"
  num_arm_joints: 6
  arm_joint_limits_max: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
  arm_joint_limits_min: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
  # Update joint limits for YAM (6 arm + 1 gripper)
  # arm_joint_limits_max: [3.14159, 3.14159, -0.94, 1.92, 1.54, 3.14159]
  # arm_joint_limits_min: [-3.14159, 0.0, -1.89, -1.54, -1.82, -3.14159]
  arm_joint_limits_safety_margin: 0.1
  initialization:
    # These are your new start position (URDF coordinates) - system will calculate offsets automatically
    calibration_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # The leader arm must be brought to this joint position before the follower starts mirroring the leader
    initial_match_joint_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

gripper_teleop:
  # The maximum range (in rad) of the leader gripper trigger
  actuation_range: 0.8

controller:
  frequency: 500
  torque_feedback:
    enable: False
    gain: 3.0
    damping: 0.0
    motor_scalar: 94.5652173913
  gravity_comp:
    enable: True
    gain: 0.8
  null_space_regulation:
    # Target position when not actively performing tasks (matches your new start position)
    null_space_joint_target: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    kp: 0.0
    kd: 0.0
  static_friction_comp:
    enable_speed:   0.3
    gain: 0.1
  joint_limit_barrier:
    kp: 0.0
    kd: 0.0
  joint_position_control:
    interpolation_step_size: 0.5
    kp: 1.03561658022
    kd: 0.04315069084

  gripper_feedback:
    enable: False 