agent:
  _target_: gello.agents.gello_agent.GelloAgent
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    gripper_config:
    - 7
    - !!python/object/apply:numpy._core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
        - f8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - !!binary |
        AAAAAADXI8A=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        zczMzEzhP0A=
    joint_ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    joint_offsets:
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        boYb8PkhCUA=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        Yf2fw3zZEkA=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        izcyj/whGUA=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        boYb8PkhCUA=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        Yf2fw3zZEkA=
    - !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        boYb8PkhCUA=
    joint_signs:
    - 1
    - 1
    - -1
    - -1
    - 1
    - 1
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U4GA-if00-port0
  start_joints:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 1.0
hz: 30
max_steps: 1000
robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
