robot:
  _target_: gello.robots.yam.YAMRobot
  channel: "can_right"

agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA2U4GB-if00-port0"  # Right Gello controller  
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # May need different offsets for right arm
    joint_signs: [1, -1, -1, -1, 1, 1]  # May need different signs for right arm
    gripper_config: [7, 0, 0]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

hz: 30